In [3]:
import matplotlib.pyplot as plt
import polars as pl
import numpy as np
from sqlalchemy import create_engine
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
%matplotlib inline
%xmode Verbose

Exception reporting mode: Verbose


In [6]:
database_url = "postgresql://user:password@localhost:5432/retail_db"
engine = create_engine(database_url)
# we split the dataset into training and test
# to do this first we have to find the cutoff date which splits the time of our data in 70/30
q_cutoff = """
WITH date_range AS (
    SELECT MIN(invoicedate) as min_date, MAX(invoicedate) as max_date
    FROM retail_db
),
duration AS (
    SELECT max_date - min_date as total_days FROM date_range
)
SELECT
    min_date + (total_days * 0.7) as cutoff_date
FROM date_range, duration
"""
cutoff_date = pl.read_database(q_cutoff, engine)[0,0]
print(f'cutoff_date: {cutoff_date}')
# then we extract RFM data from the time before cutoff and tagret monetary value from the rest and merge them to have a labeled dataset
rfm_data = pl.read_database(f"""
    SELECT
        customerid,
        COUNT(invoiceno) as frequency,
        EXTRACT(DAY FROM (DATE '{cutoff_date}' - MAX(invoicedate))) as recency,
        SUM(quantity * unitprice) as monetary
    FROM retail_db
    WHERE customerid IS NOT NULL AND invoicedate <= '{cutoff_date}'
    GROUP BY customerid
""", engine)
target_data = pl.read_database(f"""
    SELECT
        customerid,
        SUM(quantity * unitprice) as target_monetary
    FROM retail_db
    WHERE customerid IS NOT NULL AND invoicedate > '{cutoff_date}'
    GROUP BY customerid
""", engine)
# now we join the dataset and fill null values in targets with 0 (no record in target means that customer didn't spend anything after the cutoff so it is pretty logical)
final_data = rfm_data.join(target_data, on='customerid', how='left').fill_null(0)
print(final_data.describe())

cutoff_date: 2011-08-19 13:54:48
shape: (9, 6)
┌────────────┬──────────────┬────────────┬───────────┬─────────────┬─────────────────┐
│ statistic  ┆ customerid   ┆ frequency  ┆ recency   ┆ monetary    ┆ target_monetary │
│ ---        ┆ ---          ┆ ---        ┆ ---       ┆ ---         ┆ ---             │
│ str        ┆ f64          ┆ f64        ┆ f64       ┆ f64         ┆ f64             │
╞════════════╪══════════════╪════════════╪═══════════╪═════════════╪═════════════════╡
│ count      ┆ 3258.0       ┆ 3258.0     ┆ 3258.0    ┆ 3258.0      ┆ 3258.0          │
│ null_count ┆ 0.0          ┆ 0.0        ┆ 0.0       ┆ 0.0         ┆ 0.0             │
│ mean       ┆ 15286.866483 ┆ 66.5       ┆ 86.452732 ┆ 1547.710311 ┆ 958.485231      │
│ std        ┆ 1726.057843  ┆ 136.359868 ┆ 73.45242  ┆ 5888.215569 ┆ 5215.745423     │
│ min        ┆ 12346.0      ┆ 1.0        ┆ 0.0       ┆ 2.9         ┆ 0.0             │
│ 25%        ┆ 13792.0      ┆ 14.0       ┆ 24.0      ┆ 259.45      ┆ 0.0           

In [8]:
# Now we split the data
X = final_data.select(pl.col('recency'),pl.col('frequency'),pl.col('monetary')).to_numpy()
Y = final_data.get_column('target_monetary').to_numpy()
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
print("First 5 rows of Training Data:")
print(X_train[:5])

First 5 rows of Training Data:
[[254.    23.   165.94]
 [148.    16.   285.58]
 [217.    29.   689.95]
 [ 44.    22.   416.08]
 [ 13.    19.   376.55]]


In [ ]:
# Here is the process of selecting an amount of estimators - analysis showed that 200 will be best

fig, axes = plt.subplots(3, 3, figsize=(15, 12))
fig.suptitle('Stability Check: Error Curves for Different Random Seeds', fontsize=16)

axes_flat = axes.flatten()

seeds = [0,4,8,12,16,20,24,28,32]

estimator_options = [10, 50, 100, 200, 300]

print("🌲 Running Stability Check (This might take a minute)...")
final_results = []
for i, seed in enumerate(seeds):
    ax = axes_flat[i]

    results = []

    for n in estimator_options:
        model = RandomForestRegressor(n_estimators=n, random_state=seed, max_depth=5)
        model.fit(X_train, Y_train)
        preds = model.predict(X_test)
        mae = mean_squared_error(Y_test, preds)
        results.append(mae)

    ax.plot(estimator_options, results, marker='o', linestyle='-', color='teal')
    ax.set_title(f'Random Seed = {seed}')
    ax.set_ylabel('MSE')
    ax.grid(True, alpha=0.3)

    final_results.append(results)

plt.tight_layout()
plt.subplots_adjust(top=0.92) # Leave space for the big title
plt.show()

means = []
final_results = np.array(final_results)
for i in range(len(estimator_options)):
    means.append([estimator_options[i],np.mean(final_results[i,:],axis=0)])


In [ ]:
#Actual model
print(min(means, key = lambda x : x[1]))
final_model = RandomForestRegressor(n_estimators=200, max_depth=5, random_state=42)
final_model.fit(X, Y)
